services:
  db:
    image: postgres:15
    container_name: insurance_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insurance
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: insurance_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/insurance"
      MODEL_URI: "models:/insurance_cost_model@champion"
      MLFLOW_TRACKING_URI: "http://host.docker.internal:5000"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata: